<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Mobile
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2016, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */
?>

<div data-role="page" id="about">

    <div data-role="header" data-position="fixed">
        <a href="#home" class="ui-btn ui-icon-home ui-btn-icon-notext ui-corner-all">Home</a>
        <h1>About</h1>
    </div>

    <!-- TODO get content dynamically from file or database -->
    <div role="main" class="ui-content">
        <h1>OPUS 4</h1>
        <p>This is the prototype of a mobile user interface for OPUS 4. OPUS 4 is a open source software under the
            GNU General Public License for document repositories for institutions and libraries.
        </p>
        <a href="https://www.kobv.de/opus4">OPUS 4 Homepage</a>
        <h2>Contact</h2>
        <p>This application provides access to the repository of the Zuse Institut Berlin (ZIB).</p>
        <h2>Imprint</h2>
        <p>Konrad-Zuse-Zentrum für Informationstechnik Berlin</p>
        <p>Takustr. 7<br />
            D-14195 Berlin-Dahlem</p>
        <p>Tel: +49 30 841 85-0<br />
            Fax: +49 30 841 85-125</p>
        <p>bibliothek@zib.de</p>
        <p><a href="http://www.zib.de">http://www.zib.de</a></p>

        <h2>Development</h2>
        <p>The source code of OPUS 4 is hosted on GitHub.</p>

        <a href="https://github.com/opus4">OPUS4 on GitHub</a>
    </div>

</div>
