<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Solrsearch
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2016, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */
?>


<div data-role="page" id="doctypes">

    <div data-role="header" data-position="fixed">
        <a href="#home" class="ui-btn ui-icon-back ui-btn-icon-notext ui-corner-all">Back</a>
        <h1>Document Types</h1>
        <a href="#filter" class="ui-btn ui-icon-bullets ui-btn-icon-notext ui-corner-all ui-bnt-right">Filter</a>
    </div>

    <div role="main" class="ui-content">
        <ul data-role="listview" data-count-theme="a" data-inset="false">
        <?php foreach($this->facetitems as $facetitem) : ?>
            <li><a href="#"><?= htmlspecialchars($this->translate($facetitem->getText())) ?>
                    <span class="ui-li-count"><?= $facetitem->getCount() ?></span>
                </a>
            </li>
        <?php endforeach ?>
        </ul>
    </div>

</div>
