<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Mobile
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2016, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */
?>

<div data-role="page" id="all">

    <div data-role="header" data-position="fixed">
        <div class="ui-btn-left">
            <a href="#home" class="ui-btn ui-icon-back ui-corner-all">Back</a>
            <a href="#prev" class="ui-btn ui-icon-arrow-l ui-btn-icon-notext ui-corner-all">Previous</a>
        </div>
        <h1>1 - <?= count($this->matches) ?> of <?= $this->total ?></h1>
        <div class="ui-btn-right">
            <a href="#next" class="ui-btn ui-icon-arrow-r ui-btn-icon-notext ui-corner-all">Next</a>
            <a href="#filter" class="ui-btn ui-icon-bullets ui-corner-all ui-bnt-right">Filter</a>
        </div>
    </div>

    <div role="main" class="ui-content">
        <ul data-role="listview">
            <?PHP foreach( $this->matches as $match ) : ?>
            <li>
                <a href="show?id=<?= $match->getId() ?>">
                    <div class="title" style="white-space: normal"><?= htmlspecialchars($match->getAsset('title')) ?></div>
                    <p><strong>(<?= $match->getAsset('year') ?>)</strong></p>
                    <p class="authors">
                        <?PHP foreach( $match->getAsset( 'author' ) as $index => $author ) :
                            ?><?PHP if ( $index > 0 ) : ?>, <?PHP endif ?>
                            <?= htmlspecialchars($author)
                            ?><?PHP endforeach ?>
                    </p>
                </a>
            </li>
            <?PHP endforeach ?>
        </ul>
    </div>

</div>
